"""Vendor-neutral supervised-browser contracts.

Nothing in this package may import Playwright, Win32, an HTTP client or a concrete
business extension.  Core code defines the session state machine, the page
fingerprint, the origin/risk policy, the structured transaction preview and the
ports that a Desktop Companion adapter implements.
"""

from personal_assistant.core.browser.errors import (
    BrowserError,
    BrowserLimitError,
    BrowserPolicyError,
    BrowserSessionStateError,
    BrowserUnavailableError,
    NavigationDeniedError,
    PageDriftError,
    PreviewExpiredError,
    ProhibitedTransactionError,
    UnknownBrowserOutcomeError,
)
from personal_assistant.core.browser.fingerprint import (
    compute_page_fingerprint,
    page_structure_document,
)
from personal_assistant.core.browser.models import (
    DEFAULT_PREVIEW_TTL_SECONDS,
    MAX_ATTACHMENT_BYTES,
    MAX_ATTACHMENTS,
    MAX_COMMAND_DEADLINE_SECONDS,
    MAX_FIELDS,
    MAX_RENAVIGATIONS,
    MAX_SESSIONS_PER_TASK,
    MAX_SNAPSHOT_BYTES,
    PREVIEW_TTL_LIMIT_SECONDS,
    AttachmentPreview,
    BrowserLimits,
    BrowserSessionState,
    FieldChange,
    FieldValidation,
    FieldValueSource,
    FillPlan,
    PageAction,
    PageField,
    PageLink,
    PageSnapshot,
    RiskSignal,
    SubmissionOutcome,
    TransactionPreview,
    allowed_browser_transitions,
    canonical_preview_sha256,
    ensure_browser_transition,
    form_payload_sha256,
)
from personal_assistant.core.browser.policy import (
    NavigationDecision,
    OriginPolicy,
    ProhibitedCategory,
    ProhibitedMatch,
    RiskAssessment,
    assess_risk,
    classify_labels,
    escalate_risk,
    evaluate_navigation,
    normalize_origin,
    risk_rank,
    scan_text_for_prohibited_terms,
)
from personal_assistant.core.browser.ports import (
    AdapterActionSpec,
    AdapterFieldSpec,
    BrowserAdapterRecord,
    BrowserAdapterStore,
    BrowserSessionRecord,
    BrowserSessionStore,
    CompanionClickResult,
    CompanionSessionStatus,
    DesktopBrowserPort,
    TransactionAdapterDescriptor,
    validate_adapter_descriptor,
)
from personal_assistant.core.browser.session import (
    SESSION_TTL,
    BrowserSessionBroker,
    descriptor_from_document,
)

__all__ = [
    "DEFAULT_PREVIEW_TTL_SECONDS",
    "MAX_ATTACHMENTS",
    "MAX_ATTACHMENT_BYTES",
    "MAX_COMMAND_DEADLINE_SECONDS",
    "MAX_FIELDS",
    "MAX_RENAVIGATIONS",
    "MAX_SESSIONS_PER_TASK",
    "MAX_SNAPSHOT_BYTES",
    "PREVIEW_TTL_LIMIT_SECONDS",
    "SESSION_TTL",
    "AdapterActionSpec",
    "AdapterFieldSpec",
    "AttachmentPreview",
    "BrowserAdapterRecord",
    "BrowserAdapterStore",
    "BrowserError",
    "BrowserLimitError",
    "BrowserLimits",
    "BrowserPolicyError",
    "BrowserSessionBroker",
    "BrowserSessionRecord",
    "BrowserSessionState",
    "BrowserSessionStateError",
    "BrowserSessionStore",
    "BrowserUnavailableError",
    "CompanionClickResult",
    "CompanionSessionStatus",
    "DesktopBrowserPort",
    "FieldChange",
    "FieldValidation",
    "FieldValueSource",
    "FillPlan",
    "NavigationDecision",
    "NavigationDeniedError",
    "OriginPolicy",
    "PageAction",
    "PageDriftError",
    "PageField",
    "PageLink",
    "PageSnapshot",
    "PreviewExpiredError",
    "ProhibitedCategory",
    "ProhibitedMatch",
    "ProhibitedTransactionError",
    "RiskAssessment",
    "RiskSignal",
    "SubmissionOutcome",
    "TransactionAdapterDescriptor",
    "TransactionPreview",
    "UnknownBrowserOutcomeError",
    "allowed_browser_transitions",
    "assess_risk",
    "canonical_preview_sha256",
    "form_payload_sha256",
    "classify_labels",
    "compute_page_fingerprint",
    "descriptor_from_document",
    "ensure_browser_transition",
    "escalate_risk",
    "evaluate_navigation",
    "normalize_origin",
    "page_structure_document",
    "risk_rank",
    "scan_text_for_prohibited_terms",
    "validate_adapter_descriptor",
]
