"""Public, dependency-free contracts for personal-assistant extensions.

Business extensions may import this package.  They must not import
``personal_assistant.core`` or any infrastructure package from the host.
"""

from .models import (
    ArtifactHandle,
    CapabilityHandle,
    ContextHandle,
    ContextQuery,
    DeliveryReceipt,
    DomainEvent,
    DrainReport,
    EventSourceDescriptor,
    Evidence,
    ExtensionInfo,
    FormSchemaDescriptor,
    HealthReport,
    InvocationContext,
    MigrationDescriptor,
    NotificationRequest,
    Outcome,
    PollRequest,
    PollResult,
    RiskLevel,
    RuntimeContext,
    ScheduleDefinition,
    ScheduleMisfirePolicy,
    ToolDescriptor,
    ToolResult,
    WorkflowDefinition,
    from_mapping,
    to_jsonable,
)
from .protocols import (
    ContextProvider,
    EventSource,
    Extension,
    FormSchemaProvider,
    MigrationProvider,
    NotificationProvider,
    ScheduleProvider,
    ToolProvider,
    WorkflowProvider,
)

PROTOCOL_VERSION = "1"

__all__ = [
    "PROTOCOL_VERSION",
    "ArtifactHandle",
    "CapabilityHandle",
    "ContextHandle",
    "ContextProvider",
    "ContextQuery",
    "DeliveryReceipt",
    "DomainEvent",
    "DrainReport",
    "EventSource",
    "EventSourceDescriptor",
    "Evidence",
    "Extension",
    "ExtensionInfo",
    "FormSchemaDescriptor",
    "FormSchemaProvider",
    "HealthReport",
    "InvocationContext",
    "MigrationDescriptor",
    "MigrationProvider",
    "NotificationProvider",
    "NotificationRequest",
    "Outcome",
    "PollRequest",
    "PollResult",
    "RiskLevel",
    "RuntimeContext",
    "ScheduleDefinition",
    "ScheduleMisfirePolicy",
    "ScheduleProvider",
    "ToolDescriptor",
    "ToolProvider",
    "ToolResult",
    "WorkflowDefinition",
    "WorkflowProvider",
    "from_mapping",
    "to_jsonable",
]
