"""Generic host mail capability (provider and server agnostic)."""

from __future__ import annotations

from .ports import (
    MailAccountBinding,
    MailAccountNotFoundError,
    MailAccountRecord,
    MailAccountRegistry,
    MailCapabilities,
    MailDeliveryLedger,
    MailDeliveryReceipt,
    MailDeliveryRecord,
    MailDeliveryRequest,
    MailDeliveryStatus,
    MailEnvelope,
    MailError,
    MailErrorCode,
    MailFetchedMessage,
    MailFetchResult,
    MailFolder,
    MailLedgerConflictError,
    MailLedgerStateError,
    MailPolicy,
    MailReadSession,
    MailRecipientResult,
    MailRecipientStatus,
    MailReconciliationResult,
    MailReconciliationStatus,
    MailSendLeaseGuard,
    MailTransportBroker,
)

__all__ = [
    "MailAccountBinding",
    "MailAccountNotFoundError",
    "MailAccountRecord",
    "MailAccountRegistry",
    "MailCapabilities",
    "MailDeliveryLedger",
    "MailDeliveryReceipt",
    "MailDeliveryRecord",
    "MailDeliveryRequest",
    "MailDeliveryStatus",
    "MailEnvelope",
    "MailLedgerConflictError",
    "MailLedgerStateError",
    "MailError",
    "MailErrorCode",
    "MailFetchResult",
    "MailFetchedMessage",
    "MailFolder",
    "MailPolicy",
    "MailReadSession",
    "MailRecipientResult",
    "MailRecipientStatus",
    "MailSendLeaseGuard",
    "MailReconciliationResult",
    "MailReconciliationStatus",
    "MailTransportBroker",
]
